from __future__ import annotations

import subprocess


MAIN_BRANCH = "foss-main"


class GHClientError(Exception):
    pass


class GHClient:
    def __init__(self, github_token: str) -> None:
        self._env = {"GH_TOKEN": github_token, "GITHUB_TOKEN": github_token}

    def create_branch(self, repo_path: str, branch_name: str) -> None:
        self._git(repo_path, ["checkout", MAIN_BRANCH])
        self._git(repo_path, ["pull", "--ff-only", "origin", MAIN_BRANCH])
        self._git(repo_path, ["checkout", "-b", branch_name])

    def commit_files(self, repo_path: str, file_paths: list[str], message: str) -> None:
        for path in file_paths:
            self._git(repo_path, ["add", path])
        self._git(repo_path, ["commit", "-m", message])

    def push_branch(self, repo_path: str, branch_name: str) -> None:
        self._git(repo_path, ["push", "-u", "origin", branch_name])

    def open_pr(
        self,
        repo_path: str,
        branch_name: str,
        title: str,
        body: str,
        base_branch: str = MAIN_BRANCH,
    ) -> str:
        """Opens a PR and returns its URL."""
        result = self._run(
            repo_path,
            ["gh", "pr", "create",
             "--title", title,
             "--body", body,
             "--base", base_branch,
             "--head", branch_name],
        )
        # gh pr create returns the PR URL as the last line of stdout
        url = result.stdout.strip().splitlines()[-1].strip()
        if not url.startswith("https://"):
            raise GHClientError(f"Unexpected gh pr create output: {result.stdout}")
        return url

    def branch_exists_on_remote(self, repo_path: str, branch_name: str) -> bool:
        result = self._run(
            repo_path,
            ["git", "ls-remote", "--heads", "origin", branch_name],
            check=False,
        )
        return bool(result.stdout.strip())

    def get_pr_url_for_branch(self, repo_path: str, branch_name: str) -> str | None:
        result = self._run(
            repo_path,
            ["gh", "pr", "view", branch_name, "--json", "url", "--jq", ".url"],
            check=False,
        )
        url = result.stdout.strip()
        return url if url.startswith("https://") else None

    # ------------------------------------------------------------------

    def _git(self, repo_path: str, args: list[str]) -> subprocess.CompletedProcess:
        return self._run(repo_path, ["git"] + args)

    def _run(
        self,
        cwd: str,
        cmd: list[str],
        check: bool = True,
    ) -> subprocess.CompletedProcess:
        import os
        env = {**os.environ, **self._env}
        result = subprocess.run(
            cmd, cwd=cwd, capture_output=True, text=True, env=env, timeout=120,
        )
        if check and result.returncode != 0:
            raise GHClientError(
                f"`{' '.join(cmd)}` failed (exit {result.returncode}):\n{result.stderr[:400]}"
            )
        return result


def branch_name_for_issue(issue_id: str, repo_name: str) -> str:
    return f"bug-fix/plane-{issue_id[:8]}-{repo_name}"


def pr_body(issue_id: str, issue_title: str, test_path: str, plane_url: str) -> str:
    return (
        f"## Bug Fix\n\n"
        f"**Plane issue:** {plane_url}\n\n"
        f"**Summary:** {issue_title}\n\n"
        f"## Reproduction test\n\n"
        f"```\n{test_path}\n```\n\n"
        f"Run with:\n"
        f"```bash\ncd foss-sso-e2e && npx playwright test {test_path}\n```\n\n"
        f"---\n_Generated by the bug-fixer agent._"
    )
